"""Rewrite the generated questions so they stop giving away the answer's row label.

The training set was built by the organisers' `legacy` engine, which locks a fact
whose `metric_name` is read off the row label and then phrases a question around
that name. Measured on our own pairs: **45.1% of questions contain the answer's
row label almost verbatim**. The adapter trained on them scored 62.9% on held-out
and lost 16 questions on the real exam, because it had learned to copy a phrase it
was handed rather than to find one.

The exam is different by construction. It was generated by the `paper` engine,
whose stage 3 states: "You do not have access to the CSV content or to the row and
column labels." Across all 1,012 exam questions there are zero that ask for a
company name (stage 3 forbids it), zero open-ended ones, and 53 that ask for a
reporting period (stage 3 allows it) — no exceptions, which is how we know.

Regenerating with the `paper` engine is not affordable in time: it runs
`for _ in range(count)` with no parallelism, at 47 s per call and ~5 calls per
kept record — 20 hours for 100 records, weeks for a training set.

But the expensive part of that engine is choosing and validating the fact, and our
facts are already locked and execution-verified. Only the wording is wrong. So this
redoes stage 3 alone: one short call per record, no tables in the prompt, ~$0.09
for the whole set.

Faithfulness is the risk, not cost. A paraphrase that widens the meaning makes the
locked answer wrong for the new question, and nothing downstream would catch it —
the execution gate only re-runs the query, which still returns the same cell. So
the prompt fixes company, period, unit and scope verbatim and asks only for the
*metric* to be said the way an analyst would say it, and `--check` samples the
result for review before anything is trained on it.

Usage:
  PYTHONPATH=src python scripts/rewrite_questions.py \
      --records artifacts/easy_full.jsonl --out artifacts/easy_reworded.jsonl
"""

from __future__ import annotations

import argparse
import json
import re
import sys
import threading
import time
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from vifin.answering import lookup as lookup_mod  # noqa: E402
from vifin.llm.client import ChatClient  # noqa: E402
from vifin.query.companies import strip_tones  # noqa: E402
from vifin.store import TableKey, TableStore  # noqa: E402

SYSTEM = """Bạn là chuyên gia phân tích báo cáo tài chính Việt Nam.

Nhiệm vụ: viết lại một câu hỏi tài chính sao cho nó hỏi ĐÚNG cùng một số liệu, nhưng \
diễn đạt khoản mục theo cách một nhà phân tích sẽ nói, thay vì chép nguyên văn tên dòng \
trong bảng báo cáo.

Bắt buộc giữ nguyên, không được đổi:
- tên doanh nghiệp và mã chứng khoán
- kỳ hoặc thời điểm (năm, "cuối năm", "đầu năm")
- đơn vị được hỏi (tỷ đồng, triệu đồng, %, ...)
- phạm vi báo cáo (công ty mẹ hay hợp nhất)

Chỉ được đổi cách gọi khoản mục. Dùng từ ngữ tài chính phổ thông, đồng nghĩa, hoặc cách \
diễn đạt tự nhiên. Câu hỏi phải vẫn chỉ ra duy nhất một số liệu — không được mở rộng \
thành nhiều khoản mục hay thành một khái niệm rộng hơn.

Chỉ trả về một dòng duy nhất là câu hỏi đã viết lại. Không giải thích, không JSON, không suy luận."""

USER = """Câu hỏi gốc: {question}

Khoản mục này trong bảng được ghi là: "{label}"

Viết lại câu hỏi sao cho KHÔNG dùng lại cụm từ "{label}", nhưng vẫn hỏi đúng số liệu đó.

/no_think"""

JSON_RE = re.compile(r"\{.*?\}", re.S)


def extract_question(reply: str) -> str:
    """Pull the rewritten question out, whatever shape the reply arrives in.

    Qwen3-14B reasons in bare prose here — no `<think>` tags for a parser to
    strip — so a 512-token budget was spent deliberating and the answer never
    appeared. Six of seven calls "failed" for that reason and not because the
    model could not do the task. Accept JSON if it came, otherwise the last line
    that reads like a question.
    """

    text = re.sub(r"<think>.*?</think>", " ", reply, flags=re.S).strip()
    match = JSON_RE.search(text)
    if match:
        try:
            value = json.loads(match.group(0)).get("question", "")
            if value:
                return str(value).strip()
        except Exception:
            pass
    lines = [ln.strip().strip('"') for ln in text.splitlines() if ln.strip()]
    for line in reversed(lines):
        if line.endswith("?") and len(line) > 25:
            return line
    return ""


def norm(text: str) -> str:
    return re.sub(r"[^a-z0-9 ]", " ", strip_tones(str(text)).lower())


def leaks(question: str, label: str) -> bool:
    """Does the question hand over the label's content words?

    The same test that measured 45.1% on the original set, so before and after are
    comparable. Words of four letters or more only: "chi" and "phi" appear
    everywhere and matching on them would call every question a leak.
    """

    words = [w for w in norm(label).split() if len(w) > 3]
    if not words:
        return False
    text = norm(question)
    return sum(1 for w in words if w in text) / len(words) >= 0.8


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--records", default="artifacts/easy_full.jsonl")
    parser.add_argument("--out", default="artifacts/easy_reworded.jsonl")
    parser.add_argument("--model", default="qwen/qwen3-14b")
    parser.add_argument("--workers", type=int, default=10)
    parser.add_argument("--limit", type=int, default=0)
    args = parser.parse_args()

    store = TableStore.load(ROOT / "artifacts" / "tables.parquet")
    records = [
        json.loads(line)
        for line in Path(args.records).read_text(encoding="utf-8").splitlines()
        if line.strip()
    ]
    if args.limit:
        records = records[: args.limit]

    # The label is what the query reads, so it is found the same way `build_sft`
    # finds it: run the recorded answer back to a cell, then read that row's label.
    work = []
    skipped = 0
    for record in records:
        try:
            doc_name, table_id = record["relevant_tables"][0].rsplit("|table_", 1)
            grid = store.rows(TableKey(doc_name, int(table_id)))
        except Exception:
            skipped += 1
            continue
        if not grid:
            skipped += 1
            continue
        label_col = lookup_mod.label_column(grid)
        wanted = str(record["answer"]).strip()
        label = ""
        for line in grid[1:]:
            if any(str(cell).strip() == wanted for cell in line):
                if label_col < len(line):
                    label = str(line[label_col]).strip()
                break
        if not label:
            # No row label to leak; the question cannot give away what is not there.
            work.append((record, ""))
            continue
        work.append((record, label))

    leaking = [(r, l) for r, l in work if l and leaks(r["question"], l)]
    print(f"{len(work)} records ({skipped} unreadable), "
          f"{len(leaking)} leak their label = {len(leaking) / max(len(work), 1):.1%}")
    print(f"rewriting the {len(leaking)} that leak\n")

    client = ChatClient.from_env(ROOT, model=args.model, max_tokens=1200)
    lock = threading.Lock()
    counts = {"ok": 0, "still_leaks": 0, "failed": 0}
    started = time.time()
    rewritten: dict[int, str] = {}

    def rewrite(item) -> None:
        record, label = item
        try:
            reply = client.complete(
                SYSTEM, USER.format(question=record["question"], label=label))
            question = extract_question(reply)
        except Exception:
            with lock:
                counts["failed"] += 1
            return
        if not question:
            with lock:
                counts["failed"] += 1
            return
        with lock:
            counts["ok"] += 1
            if leaks(question, label):
                counts["still_leaks"] += 1
            rewritten[id(record)] = question
            done = counts["ok"] + counts["failed"]
            if done % 50 == 0:
                print(f"  {done}/{len(leaking)}  still leaking "
                      f"{counts['still_leaks'] / max(counts['ok'], 1):.1%}  "
                      f"{time.time() - started:.0f}s", flush=True)

    with ThreadPoolExecutor(max_workers=args.workers) as pool:
        list(pool.map(rewrite, leaking))

    out_path = ROOT / args.out
    changed = 0
    with out_path.open("w", encoding="utf-8") as handle:
        for record, label in work:
            new = rewritten.get(id(record))
            if new:
                record = {**record, "question": new, "question_original": record["question"]}
                changed += 1
            handle.write(json.dumps(record, ensure_ascii=False) + "\n")

    total_leak = sum(1 for record, label in work
                     if label and leaks(record.get("question", ""), label))
    print(f"\n  rewritten {changed}, failed {counts['failed']}")
    print(f"  leak rate: {len(leaking) / max(len(work), 1):.1%} -> "
          f"{total_leak / max(len(work), 1):.1%}")
    print(f"\nwrote {out_path}")
    print("  Read a sample before training on it: a paraphrase that widens the")
    print("  meaning makes the locked answer wrong for the new question, and the")
    print("  execution gate cannot see that — it only re-runs the same query.")


if __name__ == "__main__":
    main()
