"""One line per shipped answer, carrying just enough to judge it by eye.

The gold set this project measured against was generated by an LLM writing a question
about a cell the pipeline had already chosen, and the execution gate cannot notice a
question that names a different line item than the cell it was built from. Measured:
48% of its gold rows share no words with the question's metric, and hand-reading found
"Chi phí nhân sự" pointing at "Chi phí khấu hao". So every offline number this project
reported rests on a reference that is partly wrong.

The only trustworthy reference is the real exam wording, judged by hand. `trace_answer`
prints enough to do that but spends thirty lines a question. This prints one, so a
batch of thirty can be read at once:

  id=215  hỏi 'Chứng chỉ tiền gửi'  ->  dòng 'Tiền gửi của khách hàng' | cột 'Tổng' | 726021696.0

The judgement is whether the row label means what the question asks. That is the step
the measurements disagree about, and it is the one a reader can settle in a second.

Usage:
  PYTHONPATH=src python scripts/verify_compact.py --base aimed.zip --n 30 --seed 7
  PYTHONPATH=src python scripts/verify_compact.py --base aimed.zip --ids 215,578
"""

from __future__ import annotations

import argparse
import json
import random
import sys
import zipfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))
sys.path.insert(0, str(ROOT / "scripts"))

from trace_answer import logged_reads, read_grid  # noqa: E402

from vifin.answering import lookup as lookup_mod  # noqa: E402
from vifin.query.companies import CompanyRoster  # noqa: E402
from vifin.query.parse import parse_question  # noqa: E402


def main() -> None:
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    parser = argparse.ArgumentParser()
    parser.add_argument("--base", required=True)
    parser.add_argument("--n", type=int, default=30)
    parser.add_argument("--seed", type=int, default=7)
    parser.add_argument("--ids", default="")
    parser.add_argument("--single", action="store_true",
                        help="only questions naming at most one company")
    parser.add_argument("--max-reads", type=int, default=2)
    args = parser.parse_args()

    import pandas as pd

    roster = CompanyRoster.load(ROOT / "data" / "code_stock.csv")
    done = set()
    reference = ROOT / "artifacts" / "hand_verified.jsonl"
    if reference.exists():
        for line in reference.read_text(encoding="utf-8").splitlines():
            if line.strip():
                done.add(json.loads(line)["id"])

    with zipfile.ZipFile(ROOT / "submissions" / args.base) as archive:
        payload = json.loads(archive.read("submission.json").decode("utf-8"))
        rows = payload if isinstance(payload, list) else (
            payload.get("predictions") or list(payload.values())[0])

        if args.ids:
            keep = {int(p) for p in args.ids.split(",") if p.strip()}
            pool = [r for r in rows if r["id"] in keep]
        else:
            pool = [r for r in rows if r["id"] not in done]
            if args.single:
                pool = [r for r in pool
                        if len(set(parse_question(0, r["question"], roster).tickers)) <= 1]
            random.Random(args.seed).shuffle(pool)
            pool = pool[: args.n]

        print(f"{len(pool)} câu (đã bỏ {len(done)} câu đã phán)\n")
        for row in pool:
            metric = lookup_mod.extract_metric(row["question"])
            frames = {}
            for item in row.get("evidence") or []:
                try:
                    grid = read_grid(archive, item["csv_path"])
                except KeyError:
                    continue
                if grid:
                    frames[item["variable"]] = pd.DataFrame(grid[1:], columns=grid[0])
            reads = logged_reads(row.get("pandas_query") or "", frames)
            seen, cells = set(), []
            for variable, r_i, c_i, cell in reads:
                if (variable, r_i, c_i) in seen:
                    continue
                seen.add((variable, r_i, c_i))
                frame = frames.get(variable)
                label = header = "?"
                if frame is not None:
                    try:
                        label = str(frame.iloc[r_i, 0])[:44]
                    except Exception:  # noqa: BLE001
                        label = "<ngoài bảng>"
                    columns = list(frame.columns)
                    header = str(columns[c_i])[:24] if c_i < len(columns) else "?"
                cells.append(f"{label!r} | {header!r}")
                if len(cells) >= args.max_reads:
                    break
            trace = "  ;  ".join(cells) if cells else "<không truy được ô>"
            print(f"id={row['id']:<5d} {metric[:46]!r}")
            print(f"        -> {trace}")
            print(f"        nộp={row.get('answer')}  ({len(seen)} ô)")


if __name__ == "__main__":
    main()
